### ISSUE TITLE
This looks awesome, but we need to be able to reset the checklist...

### ISSUE THREAD

**Issue by arretx** [leibler/dokuwiki-plugin-todo#130]
One of the features that would be excellent would be the ability to differentiate between a task and a checklist item.

For instance, a task might be "Install new widget on airplane."  For that, it will be completed one time.

Now, on a weekly basis, we would need to complete another task:  "Check airplane widget"  BUT that task would involve a few steps, which would be checklist items.

Task:  Check Airplane Widget (Recurring Weekly)
Checklist Items:
  * Is the Widget Hot?
  * Is the Widget Green?
  * Rotate the widget.

So, the task would be something like, fly to Denver.  The checklist would be the flight checklist, which wouldn't need to be completable tasks, but just items on a checklist.

Then, to complicate things, the task that the checklist items are under wouldn't be able to be completed until all of the checklist items were checked.

Then, to complicate things even more, the main task would be recurring, and would re-set at a given time prior to the next task date to make room for the repeated process.

Not to complicate things or anything.  ;).

**Comment by runout-at** [comment]
I didn'd see this until now.

**Comment by einhirn** [comment]
@arretx 's feature request is really out of scope for this plugin. I recognize some of what he describes from a todo-list-app, which is a specialized tool. This is a plugin to add some functionalitiy to a wiki - but at some point you need to put the hammer away otherwise every problem will look like a nail...

"wiki" - which is Hawaian for "fast/quick", and I don't see any good way to implement a fully featured todo list app based on a text file based wiki app and still have "fast/quick" (easy) apply to it...
