### ISSUE TITLE
Conflict with Dokuwiki Blog plugin

### ISSUE THREAD

**Issue by pmgeuze** [leibler/dokuwiki-plugin-todo#137]
Hello friends,

Thank you for a great plugin. I have noticed that when I have the Blog plugin on a page and any of the Blog entries contains a ToDo task, that when I 'check' the ToDo task that it will show checked. When I refresh the page, the ToDo item is unchecked, and that the ToDo text that marks an item as checked is instead inserted after the greater than symbol in the Blog command.

```
{{blog  #pmgeuze:2021-10-18>journal&fullpage}}

----

===== To Do Tasks =====

~~TODOLIST completed:no  header:firstheader~~
```

This text insert will then break the Blog command and does not mark the ToDo task either.

I hope that this is somehow a simple fix, but I appreciate that it may be complicated due to the nesting issue. I enjoy using your ToDo as an addition to my Journal (Blog).

**Comment by runout-at** [comment]
I don't use the blog plugin, so i don't know anything about its details.

Can you verify that the blog plugins isn't preventing the code change or is overwriting the change?

Did you report this issue for the blog plugin?

**Comment by runout-at** [comment]
If there is no further response I'll close this soon.

**Comment by einhirn** [comment]
It's really an edge case, but if we rework https://github.com/leibler/dokuwiki-plugin-todo/blob/4f36f53781bbdb074262766d94d2404836f3e16d/action.php#L134C25-L135C25 we could at least prevent the impact on the blog plugin's syntax (or any other page nesting syntax). But it wouldn't fix the issue that the Todo item would be unchecked again after reload, because we have no (known) way to determine which page ID the Todo was nested from...

@pmgeuze Oh, and the workaround would be to just add a Todo at the bottom of the "main" blog page (where you put the blog plugin syntax...)

**Comment by einhirn** [comment]
As explained in the PR's message this isn't perfect but will prevent todos nested from a different page to break the page nesting them - as long as the nesting page doesn't use todos also...
