### ISSUE TITLE
Reset / (un)check all boxes

### ISSUE THREAD

**Issue by AdosJ** [leibler/dokuwiki-plugin-todo#158]
Hello,

not a bug, but request for a feature:

A button to check or uncheck all boxes in a batch - or a button to reset checked boxes to unchecked state.

I use the checkboxes in a checklist for official certification of signatures. The reset button would help to remove all the checks before new process of certification.

Thank you.

**Comment by einhirn** [comment]
This feature is available now, thanks to @RobertWeinmeister

**Comment by ibot87** [comment]
Works great, thank you for your work.
This feature could be mentioned on the Dokuwiki Plugin Page.

Possible improvement: if there are several TODO-Lists on a single page (in my case very helpful packing lists for vacation for several family members), these "sub-lists" could be uncheckable instead of all todos on the page at once.

**Comment by einhirn** [comment]
Feel free to build on the now existing code for this feature.
