### ISSUE TITLE
extra plug-in 'search pattern' advertised but out of use since 2014

### ISSUE THREAD

**Issue by Zweihorn** [leibler/dokuwiki-plugin-todo#171]
Please **update the advertisement info text** of this plug-in.

NB 🤣  Happy ten years and time flies ...

Obviously, the extra plug-in 'search pattern' is currently advertised but apparently **out of use since the year 2014** and quite outdated. I would call this somewhat misleading and quite unfortunate.

The erroneous advertisement text "In combination with **dokuwiki searchpattern plugin** it is a lightweight task list management system." should be deleted asap, I presume.

Please find the output of the DokuWiki Extension Manager for the 'dokuwiki-plugin-todo' in a current 2024-02-06 "Kaos" install as below:
![Bildschirmfoto 2024-04-27 um 22 05 02](https://github.com/leibler/dokuwiki-plugin-todo/assets/4863737/1dc6a3d8-1e92-4909-940b-611da8ce2086)

ref https://github.com/leibler/dokuwiki-plugin-todo/issues/26#issuecomment-46091351 from 2014

Furthermore, the section on "Lightweight Task Management System - Lists" could state the obsolescence of the a.m. plug-in explictily, if I may.

> Lightweight Task Management System - Lists
>
> The new version (since version 2014-03-17) of the todo plugin allows to create an easy to use task management system to collect all todos from all pages on a single page.

Thus, I felt free to add some text for clarity as:
"The former extra plug-in 'search pattern' was **intentionally made obsolete** by this version."

ref https://www.dokuwiki.org/plugin:todo#lightweight_task_management_system_-_lists

Keep on the good work and prosper.

Hope this helps.
🌻

**Comment by Zweihorn** [comment]
Last not least using the `~~INFO:syntaxplugins~~ ` macro on a wiki page would state the same.

![Bildschirmfoto 2024-04-27 um 22 45 27](https://github.com/leibler/dokuwiki-plugin-todo/assets/4863737/6eb0db4e-0f0a-4c09-96ca-75c494f2f5a6)

Poor newbie user people, I would understand any confusion.

**Comment by einhirn** [comment]
Great job spotting outdated information in the plugin description

Back when the feature was new, this update instruction was added to the [plugin:todo page](https://www.dokuwiki.org/plugin:todo?rev=1395088347):
>Update Instructions: Since version 2014-03-17 the searchpattern integration is deprecated. Use the new ~~TODOLIST~~ built-in method.

But I removed note in [February 2020](https://www.dokuwiki.org/plugin:todo?rev=1581003198) - probably because that change was so long ago.

Anyway, I went ahead and changed the wording of the notice you added to the plugins page, because your addition sounded as if we intended to make the searchpattern plugin itself obsolete with this feature - which obviously isn't the case. We just deprecated it for the listing of todos because of incompatibilities.

**Comment by Zweihorn** [comment]
Looks good to me and THX.

**Comment by Zweihorn** [comment]
@einhirn Please consider a release for availability as an usual DokuWiki Plug-In update at your earliest convenience.

**Comment by einhirn** [comment]
[X] done. I guess I was waiting for some code change before creating a new release - but making a maintenance release without code change is probably better than waiting indefinitely. Maybe there are people out there still trying to make this work with searchpattern because of the outdated infos and can't or don't know how to tell us about it, like you did.

**Comment by einhirn** [comment]
It's not even a maintenance release any more - we still had a PR with a new feature in the pipeline, which just needed some cleanup before merging.
