### ISSUE TITLE
Marking a TODO by a colored label

### ISSUE THREAD

**Issue by Juergen-Vollmer** [leibler/dokuwiki-plugin-todo#46]
Ist there a way to mark a TODO as e.g. "error"  or "nice to have" etc. It would be nice if it is displayed  like the user anme or due date. That label sould be colored in red or green, etc. 
Nice to have would be a searchpattern like
  ~ ~ TODOLIST label:error ~ ~
or
  ~ ~ TODOLIST label:wish ~ ~

with best regards

Jürgen

**Comment by runout-at** [comment]
The idia is good. but we should think about some implications.

Can we have more than one label per task like 'tags' or 'classes'? (comma separated)
Is the list of tags predefined somewhere?
if a label can be named freely, where will the corresponding color be defined?
How will we manage the colors (css-classes)?

As a workaround you could use a user instead of a label. like @error or @nice_to_have. just no coloring.

**Comment by Juergen-Vollmer** [comment]
> Can we have more than one label per task like 'tags' or 'classes'? (comma separated)

would be nice

> Is the list of tags predefined somewhere?
not neccaray, onw could use "speaking names", or one could define them in the configuration

> if a label can be named freely, where will the corresponding color be defined?
> How will we manage the colors (css-classes)?

using the configuration section would be better (to remeber the place for (re)defining colors)

> As a workaround you could use a user instead of a label. like @error or @nice_to_have. 
> just no coloring. 

that's the way I've done it currently
