### ISSUE TITLE
rare permission denied when saving with todo tag

### ISSUE THREAD

**Issue by armanabraham** [leibler/dokuwiki-plugin-todo#77]
Stumbled into a weird bug. Typing this: 

< todo >Mark text as ToDo< /todo >
from warehouse. 

and saving it gives me "Forbidden: You don't have permission to access /wiki/doku.php on this server.". If I remove "from" or "warehouse" or the < todo > there is no problem saving the page. 

I am running the latest stable version of Dokuwiki and my web host is nexcess.com

**Comment by runout-at** [comment]
I can not reproduce this. todo-plugin version: 2017-01-06

**Comment by jpindar** [comment]
This is probably because your server is running a web application firewall such as ModSecurity.  You'll have to either find a setting for it in your hosting control panel or ask the admin to change it for you. It may be possible to change it for only /wiki, not your whole domain.

Here's what Namecheap has to say about it: https://www.namecheap.com/support/knowledgebase/article.aspx/9542/22/what-is-modsecurity-and-why-do-we-need-it
