### ISSUE TITLE
Todolist from two differents namespaces

### ISSUE THREAD

**Issue by Digitalin** [leibler/dokuwiki-plugin-todo#79]
Hello, 
I would like to list todo from :bar and  :foo, not sure it is possible. So, I tried using ns:foo :bar and different possibilities without success. It takes only the first namespace after ns:
The other mean seems to exclude namespaces, with `ns:/` but it is an enhancement in progress.
I don't know enough Regex (PCRE) as if it could possible with the  searchpattern : 
`~~TODOLIST SEARCHPATTERN# '/<todo>[^>]*>.*?<\/todo[\W]*?>/'?? _todo ?? ~~` to specify namespaces to limit search to certain paths or depth. 
By the way, todo plugin is a must for Dokuwiki and I just begin using it, with the minimum features. So cool. 
Thanks.

**Comment by runout-at** [comment]
i remember something about a 'searchpattern plugin' but i don't know if this still works.

for the `ns:` syntax you are right. it's not possible to include more than one namespace.
i had the idea of searching more namespaces too but this gets quite complex and i didn't have the time to do it in the end.
searching big or more namespaces can be very time consuming. i tried my best to exclude pages and subnamespaces as early as possible when they are checked because there is a recursion through all subnamespaces which can lead to horrible response times.

still there should be done some documentation about the `ns:` feature. afair i did not write evrything in the wiki.

**Comment by runout-at** [comment]
I found this comment in `syntax/todo.php` which looks similar to what you have in the original post.
did you try this approach?

```
In combination with dokuwiki searchpattern plugin version (at least v20130408),
it is a lightweight solution for a task management system based on dokuwiki.
use this searchpattern expression for open todos:
    ~~SEARCHPATTERN#'/<todo[^#>]*>.*?<\/todo[\W]*?>/'?? _ToDo ??~~
use this searchpattern expression for completed todos:
    ~~SEARCHPATTERN#'/<todo[^#>]*#[^>]*>.*?<\/todo[\W]*?>/'?? _ToDo ??~~
do not forget the no-cache option
    ~~NOCACHE~~
```

**Comment by Digitalin** [comment]
Hi,
Tanks for your response. Just later my post, I found a simple solution : 
`~~NOCACHE~~`
`~~TODOLIST ns:foo~~` 
`~~TODOLIST ns:bar~~` 
that gives exactly what I need. No more code :-)

The `~~SEARCHPATTERN#......~~` alone  doesn't work for me but works well with TODOLIST before. I don't see difference with the new pattern you offer :
`~~TODOLIST SEARCHPATTERN#'/<todo[^#>]*>.*?<\/todo[\W]*?>/'?? _ToDo ??~~`
`~~TODOLIST SEARCHPATTERN#'/<todo[^#>]*#[^>]*>.*?<\/todo[\W]*?>/'?? _ToDo ??~~` . In both cases, it is displaying all todos (opened and completed tasks). 
But the flag `completed:yes|no` works well. So, it is ok for me.  Regex should be really usefull to search with some special words  (I see tags is in the wishlist)
In the [Plugin todo Dokuwiki documentation](https://www.dokuwiki.org/plugin:todo#lightweight_task_management_system), it could be nice to add at the end of ns section the simple solution for displaying chosen namepaces.
